Repository AY2324S2-CS2103T-F12-2/tp, pull requests merged in 2024-04, with the labels that each got.

#63 Add test util classes for articles
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/articlecommands/ArticleCommandTestUtil.java
  src/test/java/seedu/address/testutil/ArticleBookBuilder.java
  src/test/java/seedu/address/testutil/ArticleBuilder.java
  src/test/java/seedu/address/testutil/EditArticleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalArticles.java
Labels: priority.High, type.Task

#92 Add Lookup Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LookupCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/LookupArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArticleBookParser.java
  src/main/java/seedu/address/logic/parser/LookupArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/LookupCommandParser.java
  src/main/java/seedu/address/model/ArticleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/ArticleWithinPersonPredicate.java
  src/main/java/seedu/address/model/article/UniqueArticleList.java
  src/main/java/seedu/address/model/person/NameWithinArticlePredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#94 Branch kk fix feature flaws
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/FilterArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/RemoveArticleFilterCommand.java
  src/main/java/seedu/address/logic/parser/ArticleBookParser.java
  src/main/java/seedu/address/logic/parser/FilterArticleCommandParser.java
  src/main/java/seedu/address/model/article/ArticleMatchesStatusPredicate.java
Labels: priority.High, severity.Medium

#100 Implement dynamic UI spacing
  src/main/java/seedu/address/ui/ArticleCard.java
  src/main/resources/view/ArticleListCard.fxml
Labels: severity.VeryLow, type.Task

#96 Fix feature flaws for duplication detection and case sensitivity
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Title.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, type.Enhancement

#98 Add Link feature
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/Link.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/main/java/seedu/address/ui/ArticleCard.java
  src/main/resources/view/ArticleListCard.fxml
  src/test/java/seedu/address/logic/commands/articlecommands/ArticleCommandTestUtil.java
  src/test/java/seedu/address/testutil/ArticleBuilder.java
  src/test/java/seedu/address/testutil/EditArticleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalArticles.java
Labels: priority.High, type.Task

#105 Add Lookup Features to UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/AddArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
Labels: documentation

#103 Update user guide with filter command
  docs/UserGuide.md
Labels: documentation

#109 Add link feature to the userguide
  docs/UserGuide.md
  docs/images/LinkFeatureSample.png
Labels: documentation

#110 Edit User guide table for commands
  docs/UserGuide.md
Labels: documentation

#112 Add descriptions for sorting persons by name and sorting articles by publication date in the UG
  docs/UserGuide.md
Labels: documentation, priority.High

#117 Fix case-sensitivity bug for sort commands
  src/main/java/seedu/address/logic/parser/SortArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/article/UniqueArticleList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: priority.High, severity.Low, type.Bug

#212 Fix some issues brought up by testers regarding filter
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/articlecommands/FilterArticleCommand.java
Labels: severity.Medium, type.DocumentationBug

#224 Add images for sort commands in UG
  docs/UserGuide.md
  docs/images/afterSortingArticles.png
  docs/images/afterSortingPeople.png
  docs/images/beforeSortingArticles.png
  docs/images/beforeSortingPeople.png
Labels: severity.Low, type.DocumentationBug

#220 Fix bug when parsing article commands
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: severity.Medium, type.FunctionalityBug

#216 Making bug fixes and additions to the DG
  docs/DeveloperGuide.md
  docs/diagrams/SortArticlesSequenceDiagram-Logic.puml
  docs/diagrams/SortArticlesSequenceDiagram-Model.puml
  docs/diagrams/SortPersonsSequenceDiagram-Logic.puml
Labels: documentation, priority.High

#217 Fix some UG documentation bugs
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: documentation

#213 Fix incorrect editing of hidden persons attribute
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/article/Article.java
Labels: bug, severity.High

#214 Bug fix for allowing invalid dates as input
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug, severity.Medium

#226 Added documentation of prefix handling
  docs/UserGuide.md
Labels: documentation

#229 UG edited for some bugs and new warning
  docs/UserGuide.md
  docs/images/UiDescription.png
Labels: documentation

#222 Add test classes
  src/main/java/seedu/address/model/article/ArticleMatchesTagPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/test/java/seedu/address/logic/commands/articlecommands/ArticleCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/articlecommands/FilterArticleCommandTest.java
  src/test/java/seedu/address/model/article/ArticleMatchesStatusPredicateTest.java
  src/test/java/seedu/address/model/article/ArticleMatchesTagPredicateTest.java
  src/test/java/seedu/address/model/article/ArticleMatchesTimePeriodPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedArticleTest.java
  src/test/java/seedu/address/testutil/TypicalArticles.java
  src/test/java/seedu/address/testutil/TypicalPredicates.java
Labels: type.Task

#231 Fix hyperlink in UG
  docs/UserGuide.md
Labels: documentation

#234 Add empty headline warning to UG
  docs/UserGuide.md
Labels: documentation

#241 Edit DG for link features
  docs/DeveloperGuide.md
  docs/diagrams/LinkSequenceDiagram.puml
Labels: documentation

#247 Update UG
  docs/UserGuide.md
  docs/images/sampleData.png
Labels: documentation, severity.High

#242 Added tests for Title, Author, Outlet and Source classes
  src/main/java/seedu/address/model/article/Title.java
  src/test/java/seedu/address/model/article/AuthorTest.java
  src/test/java/seedu/address/model/article/OutletTest.java
  src/test/java/seedu/address/model/article/SourceTest.java
  src/test/java/seedu/address/model/article/TitleTest.java
Labels: severity.Medium, type.Task

#236 Add description for manual testing in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortArticlesSequenceDiagram-Logic.puml
  docs/diagrams/style2.puml
Labels: documentation, priority.High

#254 Branch b developer guide
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortArticlesSequenceDiagram-Logic.puml
  docs/diagrams/style2.puml
  docs/diagrams/style3.puml
Labels: documentation, priority.High

#257 Enlarge PUML diagrams
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortArticlesSequenceDiagram-Logic.puml
  docs/diagrams/style2.puml
Labels: documentation, priority.High

#262 Add more planned enhancements
  docs/DeveloperGuide.md
Labels: documentation

#264 Delete all commented out codes
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/model/article/UniqueArticleList.java
  src/main/java/seedu/address/model/person/NameWithinArticlePredicate.java
Labels: type.Task

#266 Reduce font size for Model Class diagram
  docs/DeveloperGuide.md
  docs/diagrams/style2.puml
Labels: documentation

#269 Edit size of Model Class diagram
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#271 Enlarge some UML diagrams in DG
  docs/DeveloperGuide.md
Labels: documentation

#280 Finalize the DG by adding and organizing info
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#282 Add blank lines between each planned enhancement
  docs/DeveloperGuide.md
Labels: documentation
