Repository AY2324S2-CS2103T-F12-2/tp, pull requests merged in 2024-03, with the labels that each got.

#13 Update project website
  README.md
  docs/AboutUs.md
  docs/images/Ui.png
  docs/images/bennylck.png
  docs/images/h4mes.png
  docs/images/howlong11.png
  docs/images/ko-khan.png
  docs/images/murugan-maniish.png
Labels: documentation

#15 Edit Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#9 Add use cases for adding and listing articles
  docs/DeveloperGuide.md
Labels: documentation

#18 Add use case for find article command
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#29 Add Article classes
  src/main/java/seedu/address/model/ArticleBook.java
  src/main/java/seedu/address/model/ReadOnlyArticleBook.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/UniqueArticleList.java
Labels: priority.High, type.Task

#27 Add article storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/storage/ArticleBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/main/java/seedu/address/storage/JsonArticleBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableArticleBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#25 Add article command classes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/AddArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/DeleteArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/FindArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/ListArticleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/article/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Task

#39 Add find article command description to User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: documentation, priority.High, type.Task

#44 Change window title and jar name
  build.gradle
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: severity.VeryLow, type.Bug

#57 Add support for parsing sort article command
  src/main/java/seedu/address/logic/commands/articlecommands/SortArticleCommand.java
  src/main/java/seedu/address/logic/parser/ArticleBookParser.java
  src/main/java/seedu/address/logic/parser/SortArticleCommandParser.java
Labels: priority.High, type.Enhancement

#59 Implement the sort article command
  src/main/java/seedu/address/logic/commands/articlecommands/SortArticleCommand.java
  src/main/java/seedu/address/model/ArticleBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/article/UniqueArticleList.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, type.Enhancement

#65 Fix minor bugs in ModelManager.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: severity.Medium, type.Bug

#60 Refactor Authors, Sources and Tags classes
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/Author.java
  src/main/java/seedu/address/model/article/Source.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/main/java/seedu/address/storage/JsonAdaptedAuthor.java
  src/main/java/seedu/address/storage/JsonAdaptedSource.java
  src/main/java/seedu/address/ui/ArticleCard.java
  src/main/resources/view/ArticleListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Task

#68 Minor bug fix for incorrect article tag prefix
  src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
Labels: bug, severity.High

#74 Implement Outlet article attribute as class
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/Outlet.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/main/java/seedu/address/storage/JsonAdaptedOutlet.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/ArticleCard.java
  src/main/resources/view/ArticleListCard.fxml
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Task

#75 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ParserClasses.puml
  src/main/java/seedu/address/logic/parser/DeleteArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/FindArticleCommandParser.java
Labels: documentation

#76 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/ModelFilterClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: documentation, priority.High

#79 Add description for the Sort persons feature to the Developer Guide
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/SortPersonsSequenceDiagram-Logic.puml
  docs/diagrams/SortPersonsSequenceDiagram-Model.puml
Labels: documentation, priority.High

#81 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ProposedTemplateSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: documentation, priority.High

#83 Edit Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/LinkClassDiagram.puml
Labels: documentation, priority.High

#66 Branch kk filter by status
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/SetArticleCommand.java
  src/main/java/seedu/address/logic/parser/ArticleBookParser.java
  src/main/java/seedu/address/logic/parser/SetArticleCommandParser.java
  src/main/java/seedu/address/model/ArticleFilter.java
  src/main/java/seedu/address/model/Filter.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/article/ArticleMatchesStatusPredicate.java
  src/main/java/seedu/address/model/article/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/article/exceptions/InvalidStatusException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#87 Refactor article Title as a class
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/Title.java
  src/main/java/seedu/address/model/article/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
  src/main/java/seedu/address/ui/ArticleCard.java
Labels: priority.High, type.Task

#88 Refactor article PublicationDate as a class
  src/main/java/seedu/address/logic/commands/articlecommands/EditArticleCommand.java
  src/main/java/seedu/address/logic/commands/articlecommands/FilterArticleCommand.java
  src/main/java/seedu/address/logic/parser/AddArticleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/article/Article.java
  src/main/java/seedu/address/model/article/ArticleMatchesTimePeriodPredicate.java
  src/main/java/seedu/address/model/article/PublicationDate.java
  src/main/java/seedu/address/model/util/SampleArticleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedArticle.java
Labels: priority.High, type.Task

#91 Edited css for readability
  src/main/resources/view/DarkTheme.css
Labels: enhancement, severity.Low
